services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    user: telegraf:992
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./vsphere-stats.conf:/etc/telegraf/telegraf.d/vmsphere-stats.conf
      - /var/run/docker.sock:/var/run/docker.sock
    # networks:
    #   - tig
    depends_on:
      - influxdb2
    links:
      - influxdb2
    ports:
      - '8125:8125'

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - influxdb2
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    # networks:
    #   - tig
    links:
      - influxdb2
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - 8086:8086
    # networks:
    #   - tig
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: telegraf
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: wCduKq5mQwVS3_JCg07Ljrdb6_rx_086wnJmDGRtgT2MRjII1x_-LhueLjFFXmr7mKD9EMCbti6srBjvvA81mw==
      DOCKER_INFLUXDB_INIT_ORG: QBranch
      DOCKER_INFLUXDB_INIT_BUCKET: vmware
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
# networks:
#   tig:
volumes:
  grafana_data: {}
  influxdb2-data: {}
  influxdb2-config: {}
